### ISSUE TITLE
Convert from Define-XML to Excel with ARM

### ISSUE THREAD

**Issue by sasone51** [tsClinical/tsc-desktop#2]
いつも大変お世話になっております。
ADaM用のdefine.xmlを作成する時にARMを含めることができますが、
ARMが入ったdefine.xmlからExcelを生成しても、ARM用のシート(RESULT1,RESULT2)が
含まれた状態で出てきてくれません。
そのような仕様になっているのでしょうか。
ご教示のほど、何卒よろしくお願いいたします。

**Comment by tsClinical** [comment]
お問合せありがとうございます。
「Convert from Define-XML to Excel」の機能は現状ARMに対応していません（ARMを含むDefine-XMLからRESULT1, RESULT2シートを作成することができません）。
ただ、そのような機能が期待されて当然とも思いますので（少なくともExcelからARM付きDefine-XMLを作成する事ができるので）、Feature RequestとしてIssueを起票いただければ前向きに対応させていただきます（Convert from Define-XML to Excelのソースコード自体が見づらいので書き直したいと思っていたため、その一環で機能を追加することは可能です）。

**Comment by sasone51** [comment]
---
name: Feature request
about: Suggest an idea for this project
title: 'Convert from Define-XML to Excel with ARM'
labels: '現状define.xmlのARM部分の情報がエクセル化されません'
assignees: 'sasone51'
---

**Describe the solution you'd like**
ARMを含むDefine-XMLからエクセルのRESULT1, RESULT2シートを作成させたいです。

**Describe why the solution is necessary to you, and if other people also benefit from the solution**
ARM部分のXMLコードがエクセルシート(RESULT1, RESULT2)に翻訳されたら有難いです。

**Additional context**
特にございません。

**Comment by tsClinical** [comment]
ご要望の内容はDesktop Tools v1.1.0のエンハンス要望として登録しました。本機能がリリースされた時点で本チケットをクローズさせていただきます。

**Comment by tsClinical** [comment]
Desktop Tools v1.1.0のリリースにより本エンハンス要望に対応いたしました。これにより本チケットをクローズさせていただきます。
